### ISSUE TITLE
Unclear why light doesn't show up in 2D demo scene

### ISSUE THREAD

**Issue by ancatut** [SymmetryBreakStudio/ScreenSpaceGodRays#4]
The 2D test scene apparently doesn't have a camera, so buyers of the plugin need to add one manually. And when they do, they do not know what viewing distance is necessary in order to have the lights visible in game mode.

1. Why is there no camera by default in the 2D demo scene?
2. What is the minimum camera viewing distance for the lights to be visible and why? Specify this in the documentation.

![grafik](https://github.com/SymmetryBreakStudio/ScreenSpaceGodRays/assets/7820090/d59d1a95-f3e0-4ab7-b8ae-ae583433f850)

**Comment by julhe** [comment]
Added additional info to the documentation.
